site_name: "Lucas Pereira"
site_description: "Data Scientist in the Energy Industry"
theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to light mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

nav:
  - â“ About: index.md
  - ğŸš§ Projects: projects.md
  - ğŸ“‘ CV: cv.md

plugins:
  - search

# Social media links with icons using MkDocs Material
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucasmagustopereira/
      name: "LinkedIn"
    - icon: fontawesome/brands/github
      link: https://github.com/lucarammel
      name: "GitHub"
  generator: false

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - Lucas Pereira
