site_name: "Lucas Pereira Portfolio"
site_description: "My portfolio !"
site_url: https://lucarammel.github.io/
site_dir: "public"
theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to light mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

nav:
  - ‚ùì About: index.md
  - üöß Projects: projects.md
  - üìë CV: cv.md
  - ‚òï Coffee: coffee.md

plugins:
  - search

# Social media links with icons using MkDocs Material
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucasmagustopereira/
      name: "LinkedIn"
    - icon: fontawesome/brands/github
      link: https://github.com/lucarammel
      name: "GitHub"
  generator: false

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - Lucas Pereira
